---
- name: Creating a user named {{ username }} on the specified web server (Debian).
  user: 
    name: "{{ username }}"
    password: "{{ hashed_password }}"
    state: present
    shell: /bin/bash
    groups: sudo
    append: yes
    generate_ssh_key: yes
    ssh_key_bits: 2048
    ssh_key_file: .ssh/id_rsa
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: Creating a user named {{ username }} on the specified web server (RHEL).
  user: 
    name: "{{ username }}"
    password: "{{ hashed_password }}"
    state: present
    shell: /bin/bash
    groups: wheel
    append: yes
    generate_ssh_key: yes
    ssh_key_bits: 2048
    ssh_key_file: .ssh/id_rsa
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

- name: Copy .ssh/id_rsa from host box to the remote box for user {{ username }}
  become: true
  copy: 
    src: ~/.ssh/id_rsa.pub
    dest: /home/{{ username }}/.ssh/authorized_keys
    mode: 0600
    owner: "{{ username }}"
    group: "{{ username }}"
  tags:
    - copy_host_ssh_id

- name: Add new user to sudoers list
  lineinfile:
    dest: /etc/sudoers
    regexp: "{{ username }} ALL"
    line: "{{ username }}	ALL=(ALL) 	NOPASSWD: ALL"
    state: present
